version: '3'
services:
  n8n:
    build: .
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - N8N_ENCRYPTION_KEY=superagentgael2025
    volumes:
      - ./n8n_data:/home/node/.n8n
